name: github pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.18.x
      - name: Prepare
        run: ./scripts/prepare-gh-pages
      - name: Build
        run: go run ./cmd/ssg --config gh-pages/config.json
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: gh-pages/public
          publish_branch: gh-pages
